name: Hello, World! # ワークフローの名前
on: push # push時にワークフローを実行させる

jobs: # ワークフローで実行するジョブを定義
  buildHello: # ジョブのIDを指定（一意の文字であればなんでもいい）
    name: Greeting # ジョブの名称を指定
    runs-on: ubuntu-latest # ジョブが実行される仮想環境を指定
    steps: # ジョブ内で実行される処理を定義していく
      - run: echo "Hello, World! "  # Hello, World!を表示する
